---
- name: Install and configure web server
  hosts: multipass
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
    - name: Install Git
      apt:
        name: git
        state: present

    - name: Copy Nginx Configuration Files
      copy:
       src: nginx.conf
       dest: /etc/nginx/nginx.conf
       
       #handler for nginx

      notify: Restart Nginx

  handlers:
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted



