#part 1
Vagrant.configure("2") do |config|
  # Use Ubuntu 18.04 box
  config.vm.box = "hashicorp/bionic64"
  
  # Configure VM networking
  config.vm.network "private_network", type: "dhcp"
  
  # Share a folder between host and guest
  
  config.vm.synced_folder ".", "/vagrant"
  
  # Provision VM with a shell script
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y apache2
  SHELL
end
