#cloud-config
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
      optional: true
    eth1:
      addresses:
        - 192.168.1.2/24
      gateway4: 192.168.1.1
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4]
