---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-tutorial-check-pr
spec:
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    workspaces:
    - name: source
    tasks:
      - name: fetch
        taskRef:
          name: git-clone
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
        workspaces:
          - name: output
            workspace: source
      - name: yaml-lint
        runAfter: [fetch]
        taskRef:
          name: yaml-lint
        params:
          - name: args
            value: ["."]
        workspaces:
          - name: shared-workspace
            workspace: source
  params:
    - name: repo_url
      value: {{repo_url}}
    - name: revision
      value: {{revision}}
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Mi
